echo "CREATE DATABASE IF NOT EXISTS ${POSTGRES_DB}; \
	CREATE USER ${POSTGRES_USER}@'%' IDENTIFIED BY '${POSTGRES_PASSWORD}'; \
	GRANT ALL ON ${POSTGRES_DB}.* TO ${POSTGRES_USER}@'%'; \
	FLUSH PRIVILEGES; \
	ALTER USER 'postgres'@'localhost' IDENTIFIED BY '${POSTGRES_ROOT_PASSWORD}';" > /docker-entrypoint-initdb.d/db.sql

postgres